<a href="https://colab.research.google.com/github/harshu4387/Pima-Indians/blob/main/pima_indians.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving diabetes.csv to diabetes.csv

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('diabetes.csv')

In [ ]:
df.columns=df.columns.str.lower()

In [ ]:
df.shape

(768, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pregnancies               768 non-null    int64
 1   glucose                   768 non-null    int64
 2   bloodpressure             768 non-null    int64
 3   skinthickness             768 non-null    int64
 4   insulin                   768 non-null    int64
 5   bmi                       768 non-null    float64
 6   diabetespedigreefunction  768 non-null    float64
 7   age                       768 non-null    int64
 8   outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
df.size

6912

In [ ]:
df.dtypes

pregnancies                   int64
glucose                       int64
bloodpressure                 int64
skinthickness                 int64
insulin                       int64
bmi                         float64
diabetespedigreefunction    float64
age                           int64
outcome                       int64
dtype: object

In [ ]:
df.describe()

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
df.isnull().sum()

pregnancies                 0
glucose                     0
bloodpressure               0
skinthickness               0
insulin                     0
bmi                         0
diabetespedigreefunction    0
age                         0
outcome                     0
dtype: int64

In [ ]:
df.mean(numeric_only=True)

pregnancies                   3.845052
glucose                     120.894531
bloodpressure                69.105469
skinthickness                20.536458
insulin                      79.799479
bmi                          31.992578
diabetespedigreefunction      0.471876
age                          33.240885
outcome                       0.348958
dtype: float64

In [ ]:
df.count()

pregnancies                 768
glucose                     768
bloodpressure               768
skinthickness               768
insulin                     768
bmi                         768
diabetespedigreefunction    768
age                         768
outcome                     768
dtype: int64

In [ ]:
df.dtypes

pregnancies                   int64
glucose                       int64
bloodpressure                 int64
skinthickness                 int64
insulin                       int64
bmi                         float64
diabetespedigreefunction    float64
age                           int64
outcome                       int64
dtype: object

In [ ]:
(df==0).any()

pregnancies                  True
glucose                      True
bloodpressure                True
skinthickness                True
insulin                      True
bmi                          True
diabetespedigreefunction    False
age                         False
outcome                      True
dtype: bool

In [ ]:
invalid_zero_cols = [
    'glucose', 'bloodpressure', 'skinthickness', 'insulin', 'bmi'
]

# replace 0 with nan
df[invalid_zero_cols] = df[invalid_zero_cols].replace(0, np.nan)

In [ ]:
df.sum()

pregnancies                  2953.000
glucose                     92847.000
bloodpressure               53073.000
skinthickness               15772.000
insulin                     61286.000
bmi                         24570.300
diabetespedigreefunction      362.401
age                         25529.000
outcome                       268.000
dtype: float64

In [ ]:
df.isnull().sum()

pregnancies                   0
glucose                       5
bloodpressure                35
skinthickness               227
insulin                     374
bmi                          11
diabetespedigreefunction      0
age                           0
outcome                       0
dtype: int64

In [ ]:
#  import missing values
for col in invalid_zero_cols:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipython-input-2988135526.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
df.isnull().sum()

pregnancies                 0
glucose                     0
bloodpressure               0
skinthickness               0
insulin                     0
bmi                         0
diabetespedigreefunction    0
age                         0
outcome                     0
dtype: int64

In [ ]:
(df==0).any()

pregnancies                  True
glucose                     False
bloodpressure               False
skinthickness               False
insulin                     False
bmi                         False
diabetespedigreefunction    False
age                         False
outcome                      True
dtype: bool

In [ ]:
# feature target sepration
# feature
x=df.drop('outcome',axis=1)
# target
y=df['outcome']

In [ ]:
x.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
)

In [ ]:
print(f"Shape of x_train: {x_train.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of x_test: {x_test.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of x_train: (614, 8)
Shape of y_train: (614,)
Shape of x_test: (154, 8)
Shape of y_test: (154,)

In [ ]:
y.value_counts()

outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
y_train.value_counts()

outcome
0    401
1    213
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

outcome
0    99
1    55
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

outcome
0    99
1    55
Name: count, dtype: int64

In [ ]:
y_train.value_counts(normalize=True)

outcome
0    0.653094
1    0.346906
Name: proportion, dtype: float64

In [ ]:
y_test.value_counts(normalize=True)

outcome
0    0.642857
1    0.357143
Name: proportion, dtype: float64

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [ ]:
y_pred=log_reg.predict(x_test_scaled)

In [ ]:
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
log_reg.score(x_test_scaled,y_test)

0.7532467532467533

In [ ]:
log_reg.score(x_train_scaled,y_train)

0.7703583061889251

In [ ]:
# linear regression probability prediction
y_prob=log_reg.predict_proba(x_test_scaled)

In [ ]:
y_prob[:10]

array([[0.72650648, 0.27349352],
       [0.83274552, 0.16725448],
       [0.89278831, 0.10721169],
       [0.84589992, 0.15410008],
       [0.53748186, 0.46251814],
       [0.56562556, 0.43437444],
       [0.98601508, 0.01398492],
       [0.6160686 , 0.3839314 ],
       [0.4244803 , 0.5755197 ],
       [0.23804933, 0.76195067]])

In [ ]:
y_prob_diabetic = y_prob[:, 1]
y_prob_diabetic[:20]

array([0.27349352, 0.16725448, 0.10721169, 0.15410008, 0.46251814,
       0.43437444, 0.01398492, 0.3839314 , 0.5755197 , 0.76195067,
       0.22235753, 0.89290514, 0.37535203, 0.27993186, 0.07815889,
       0.40369197, 0.11238757, 0.07377131, 0.72520049, 0.57795172])

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)
# [TN FP]
# [FN TP]

# TN - true negative-actually non dibetic
# FP - false positive-actually non diabetic but predicted diabetic
# FN - false negative-actually diabetic but predicted non diabetic
# TP - true positive-actually diabetic

array([[82, 17],
       [21, 34]])

In [ ]:




from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

# precision: how correct the model was when  it said 0 or 1
# recall: how many real 0 and 1 it found
# fitbalance: score of precision and recall
# support: how many actual 0 and 1 patients
# example for weighted avg
# classes with more sample influence the final score more than
# the smaller classes

              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154

In [ ]:
# next model we using here is svm support vector
# machine ,it finds a strong ,margin based decision
# boundary that ofetn improve recall on small,
# well scalled datasets

# the main reason to use is datasets is small in size,we did the scalling ,chances are
# high to get better recall
from sklearn.svm import SVC
svm_model=SVC(kernel='linear',probability=True)
svm_model.fit(x_train_scaled,y_train)

SVC(kernel='linear', probability=True)

In [ ]:
y_pred_svm=svm_model.predict(x_test_scaled)
# evaluating
svm_model.score(x_test_scaled,y_test)

0.7532467532467533

In [ ]:
y_prob_svm=svm_model.predict_proba(x_test_scaled)
y_prob_svm_diabetic=y_prob_svm[:,1]

In [ ]:
y_prob_svm_diabetic[:10]

array([0.29538698, 0.18293782, 0.12709623, 0.17243116, 0.4629784 ,
       0.45093765, 0.02438415, 0.37012018, 0.54754383, 0.73405134])

In [ ]:
y_pred_svm[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
y_test[:10]

668    0
324    0
624    0
690    0
473    0
204    0
97     0
336    0
568    0
148    0
Name: outcome, dtype: int64

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154

In [ ]:
from sklearn.metrics import roc_curve,roc_auc_score
roc_auc_lr=roc_auc_score(y_test,y_prob[:,1])
roc_auc_svm=roc_auc_score(y_test,y_prob_svm[:,1])
roc_auc_lr,roc_auc_svm

# 81 for both lr and sum
# roc implies that both LR and svm correctly ranks a diabetic higher than a non
# diabetic 82% of the time
# slides the threshold from 0-1,compile step,plots the curve

(np.float64(0.82277318640955), np.float64(0.8216712580348944))